logging:
  level:
    org:
      apache: ERROR
      hibernate: ERROR
      springframework: ERROR
spring:
  devtools:
    restart:
      enabled: true
    remote:
      secret: somesecret
      debug:
        local-port: 8010